version: '3.1'

services:

  mariadb-service:
    image: mariadb:10.9
    container_name: mariadb-service
    ports:
      - "3310:3306"
    hostname: mariadb-service
    environment:
      - MARIADB_USER=root
      - MARIADB_ROOT_PASSWORD=12345
      - MARIADB_DATABASE=db_app
    volumes:
      - /var/lib/mariadb:/var/lib/mysql

  app:
    build:
      context: ./
    container_name: spring-security-app
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mariadb-service
      - DB_PORT=3306
      - DB_NAME=db_app
      - DB_USERNAME=root
      - DB_PASSWORD=12345
    depends_on:
      - mariadb-service